
server:
  port: 8080

# database 연동 설정
spring:
  profiles:
    include: secret
  application: name=coffee

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름
    url: jdbc:mysql://mysql:3306/coffee_db?serverTimezone=Asia/Seoul
    username: root
    password: rootpass
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect