# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름
    url: jdbc:mysql://127.0.0.1:3306/coffee_db
    username: root
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect