name: Java Build and Deploy on develop

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # application.yaml 생성
      - name: Create application.yaml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YAML }}" > src/main/resources/application.yaml
      # Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          chmod +x ./gradlew

      # Docker 이미지 빌드
      - name: Build Docker Image
        run: docker build -t jh011007/coffee-app:develop .

      # Docker 이미지 푸시
      - name: Push Docker Image
        run: docker push jh011007/coffee-app:develop

      # 7. GCP 인스턴스에 배포
      - name: Deploy to GCP Instance via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE }}" > ~/your-project-directory/.env
            docker pull jh011007/coffee-app:develop
            docker compose down
            docker compose up -d
